# Generated by Django 4.2.9 on 2024-02-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categories_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='titile',
            new_name='title',
        ),
    ]
