# Generated by Django 4.2.9 on 2024-02-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_required',
            field=models.IntegerField(null=True),
        ),
    ]
